version: "3"

services:
  development:
    env_file:
        - .env
    build: 
      context: .
      target: development
    
    volumes: 
        - type: bind
          source: ./todo_app
          target: /todo_app/todo_app
    ports:
        - "5000:5000"

  production:
    env_file:
        - .env
    build: 
      context: .
      target: production
      
    volumes: 
        - type: bind
          source: ./todo_app
          target: /todo_app/todo_app
  
    ports:
        - "5001:5000" 